version: "3.8"
services:
  builder:
    # Docker container for building the code.
    build:
      context: .
      dockerfile: dockerfiles/ros_env.docker
    ports:
      - "1824:22"
    volumes:
      - .:/home/turtlebot/turtlebot2i